### ISSUE TITLE
XML output should use std notation for hex

### ISSUE THREAD

**Issue by sjalloq** [sdnellen/open-register-design-tool#13]
Not sure how I've not seen this before but it looks like some of the fields in the XML output are in hex but aren't prefixed with a '0x'.

For example, I have a reset value of 5'd10 which gets translated to `<reset>a</reset>`.

For now am I safe to assume these will always be in hex?

**Comment by sdnellen** [comment]
Yes, reset is hex in xml output though it's missing the 0x prefix.
