### ISSUE TITLE
Enumerattion description field missing from xml

### ISSUE THREAD

**Issue by tkafafi** [sdnellen/open-register-design-tool#21]
Please add the enumeration description field highlighted in bold to the generated xml.
Thanks

e.g RDL:
================================================
field STS  { reset = 0; hw = w;  sw = r;  }; //RO
reg {STS dma_rch_reg[1:0];} sts_fsm;
sts_fsm->desc="Finite State Machines Status Register";
sts_fsm.dma_rch_reg->desc="State of DMA Registers Read Channel statemachine";
enum fsm_dma_rch {
 STATE_IDLE       = 2'h0 **{desc = "Idle"**;};
 STATE_READ_REQ   = 2'h1 {**desc = "Request arbitration"**;};
 STATE_READ_DATA  = 2'h2 {**desc = "Data phase";**};
 STATE_ERR        = 2'h3 {**desc = "Error state";**};
};
sts_fsm.dma_rch_reg->encode=fsm_dma_rch;

Requested XML output: (add <enc_elem_desc>)
================================
        <enum_encode>
          <enc_name>fsm_dma_rch</enc_name>
          <enc_elem>
            <enc_elem_name>STATE_IDLE</enc_elem_name>
            <enc_elem_value>0x0</enc_elem_value>
            <enc_elem_desc><![CDATA[Idle]]></enc_elem_desc>
          </enc_elem>
          <enc_elem>
            <enc_elem_name>STATE_READ_REQ</enc_elem_name>
            <enc_elem_value>0x1</enc_elem_value>
            <enc_elem_desc><![CDATA[Request arbitration]]></enc_elem_desc>
          </enc_elem>
          <enc_elem>
            <enc_elem_name>STATE_READ_DATA</enc_elem_name>
            <enc_elem_value>0x2</enc_elem_value>
            <enc_elem_desc><![CDATA[Data phase]]></enc_elem_desc>
          </enc_elem>
          <enc_elem>
            <enc_elem_name>STATE_ERR</enc_elem_name>
            <enc_elem_value>0x3</enc_elem_value>
            <enc_elem_desc><![CDATA[Error state]]></enc_elem_desc>
          </enc_elem>
        </enum_encode>

**Comment by sdnellen** [comment]
submitted mod to add enc_elem_desc

**Comment by tkafafi** [comment]
Hi Scott
Can you please make a release of the jar with these updates.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
